One way to fix the problem is to create a catch(int) handler. Another way to fix it is to
catch all exceptions with a catch(...) handler.
